### PR TITLE
Class hierarchy fix and naming consistency

### PR DESCRIPTION
**Pull request by jimr**
We now have BaseColumnsHighChartsView subclass HighChartsView rathern than JSONView and call the appropraite methods on the superclass for things like context data & plot options.

Also updated a bunch of class names as per issue #12 and generally tried to improve consistency everywhere.

### CODE REVIEW

**Comment by jpic** [comment]
Nobody would agree more with me about how much this would be necessary. However, we would like a more strategic way of doing so than breaking backward compatibility.

Could we have the renames and keep aliases/compatibility with the existing names ?

**Comment by jimr** [comment]
I admit, the scope of this work changed rather dramatically as we increased our usage. If it was up to me, I'd accept the changes and bump the major version of the library to indicate the API breakage... If that's not possible, it ought to be straightforward enough to add helpers to preserve the old behaviour.

**Comment by Natim** [comment]
Can you fix the tests?

**Comment by jimr** [comment]
Are you interested in merging?

**Comment by marauder37** [comment]
It would be good to see this merged.

**Comment by Natim** [comment]
@marauder37 would you like to take it over? Merge master, clean the tests and add backward incompatibility handling with DeprecationWarnings?

**Pull request closed without merging**
